### ISSUE TITLE
Suggestion: Split Flag i

### ISSUE THREAD

**Issue by GaucheRabbit** [abyssonym/aos_rando#2]
Example:
i - Randomize items.
h - Randomize ability locations.

I would find it more empowering to have the choice of either/or instead of accepting/declining both

I also make this suggestion because I've had a few seeds already where flying armor is not in the beginning area. I might be able to damage boost over with a blue crow but that kind of thing should be reserved for chaos mode.

Problem seeds:
1494652031
1494652487

Having the choice to decline randomized ability locations would let me bypass this issue that is of course if flag i is the sole determining factor. Ultimately wouldn't solve the issue at hand of course but food for thought.

**Comment by ForOhForError** [comment]
Technically you don't need flying armor to leave the first area, just backdash:
https://www.youtube.com/watch?v=iPABgYNIyYU

But yeah more options are better.

**Comment by abyssonym** [comment]
Resolved as of https://github.com/abyssonym/aos_rando/commit/4ab3048dbdd8f2e338d7c393f2b06ae236aba9a8

I didn't exactly split the flag, but I added support for custom seeds, and included a custom seed file that will put all of the movement abilities in their original locations.

Incidentally, the seeds you posted should've been beatable, using Black Panther from the first area.
