### ISSUE TITLE
ItemObject.Superget doesn't retrieve the right indexes for special weapon modes.

### ISSUE THREAD

**Issue by DevAnj2** [abyssonym/aos_rando#6]
Just tested two seeds, and I found that for monster drops and Hammer's shop, where you used ItemObject.Superget to obtain the item index, it doesn't return the right indexes. For example, in guncula mode it returned Ascalon, Dainslef and Claimh Solais. Please investigate.

**Comment by abyssonym** [comment]
Should be taken care of now.

**Comment by abyssonym** [comment]
Wait maybe not, the fix I used shouldn't have fixed it, if there was a problem.

**Comment by abyssonym** [comment]
Okay yeah, my first instinct was correct, it is fixed now.
